### ISSUE TITLE
表格的表头 最上边一行是白色的，字都看不到了，如何改颜色

### ISSUE THREAD

**Issue by ydc1992** [winnerweb/hexo-theme-smackdown#6]
如题

**Comment by smackgg** [comment]
@ydc1992 主题前段时间在改，然后突然忙了，有些问题没改好。
表格这里确实有问题我抽时间改一下，改好了通知你。。

**Comment by qiangzhuzhu** [comment]
博主是不是不写这个了，，这么多年都没更新了

**Comment by can-dy-jack** [comment]
这个问题还没解决呀！

**Comment by Renzehua1998** [comment]
在source/css/_partial/article.styl里面改，搜索table
254行开始
```CSS
  table{
    width:100%;
    border: 1px solid #dedede;
    margin: 15px 0;
    border-collapse:collapse;
    tr,td{
      height:35px;
    }
    thead{
      tr {
        background: #f8f8f8;
      }
    }
    tbody{
      tr:hover{
        background: #efefef;
      }
    }
    td,th{
      border: 1px solid #dedede;
      padding: 0 10px;
    }
  }
```
把首栏颜色改成自己舒服的就行了
